{% set name = "python-termstyle" %}
{% set shortname = "termstyle" %}
{% set version = "0.1.11" %}
{% set compress_type = "tar.gz" %}
{% set hash_val = "ef74b83698ea014112040cf32b1a093c1ab3d91c4dd18ecc03ec178fd99c9f9f" %}
{% set build_num = 1 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.org/packages/source/{{ shortname[0] }}/{{ shortname }}/{{ shortname }}-{{ version }}.{{ compress_type }}
  sha256: {{ hash_val }}

build:
  noarch: python
  number: {{ build_num }}
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools

  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - termstyle

about:
  home: http://gfxmonk.net/dist/0install/python-termstyle.xml
  license: BSD 3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: 'Console colouring for python'
  dev_url: https://github.com/timbertson/termstyle

extra:
  recipe-maintainers:
    - pmlandwehr
