travis:
  secure:
    BINSTAR_TOKEN: tu/jTo2HhcFrmbKfNHWcsNJsMnICKjjE5iGU5+JyIzCzbk5kvYzq/sDF7CnlVrV/As51Q6GnHInFzunnnjWJCtJStOokKRTKzfyuMqALsMxYdodVn4dagSdCOgTlfcczyQejhUbYB2nOAHQ0EyCNVT4eNdBClb7j9j/eBOiMJWPIJKzefxriE6RwpTx7vUmu8fQVrgXd0IxDJiZpSU9EgjJQj/bgXMv9sAdZOLKuXPbxWyxHJk0HC8p2uFApQxvRHe5DNo1PleKQGuSxN/ibjwEseHCG12KOfHmPPomMouUpQ0rakqCGLj+c5V0PL0t/LRhja98NgdTAJ7dfwzJjWnepD3TiJi7DccfoyQPVNWG0smgCYu2c++xj2IKcx0QUEslUSJug0SvwlsCzmFrOJECdZI078GZGNIMs+jMW3ATM/DgWQbbnRWNDyfc0DWiDJAP2kb5xSrQCBKcXaTskHEQwzaQHrxaNHleP9G2tovv7wqd43wlKw3rc0/voarph1j2KSDDaIZVFURb6msw1/gHCF7fgPJxzCgy4l5bMDItDzMrUHA4znXt56AyIEcnBl0wy1tzZ4q3QCvYE2qZJUdZlrkvtcqP642zEpMW7Pqc9tHjkQW8VluV2YO8aomJCDkgEO5SAHBXKMKwC6ruzWSKdKxwu28U2On8vaz3TUEc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
