travis:
  secure:
    BINSTAR_TOKEN: YvZ8fOsHlHXsQCaqznivgYFZ0BUzLZD0z+c81LfOL/Qdcf9xs5pqnvbK9JSP20R7ozxx7OFzl8DcxEbd16sJg7adVUKFbMesB6pnBMGRZy4o8OXhqbsVdTVXI1KTvXrtPA7G0QaY99aGZqvkawDIWtgTpzRIh1evK83pBdRUzeMli4jC+f/l4CyKqvnG/P6ybfYpDFtuqmXmpYK3XnwW9++ZqfYvylrd7XJVSvnH1dxKpvdsXR21jJPgq53P5JCwyyrsGdhIUxcqQCq2ltbXmO/KvLHB65d9m2wQbC2YiYaUpugYMZh3tN0YZKvsdFHH0evBGR0kwVhxxACu1xsDugV+FbRNkDHC+JsM8hec+45KB/wiCpUqmjJ3/aRqT4Q/4WIJAY7KVfQj597oepRmNvm6QzeDZEmM1mAUdeWUUBXO6CQR0oQNtaeXunQSggwXwBUVwyTiNtOpODIDWXZ2EGOBjxq7DF04t6S104NAsSAlvnTkyFeH1WMAbLddWGmnGEVG4deMKulbQ/ZqTTAXwBEGYSWejVSRXgMNTwS1iTTrzHiZLWzFQ7duAQR23RswH9WNPlINHZ7HG8nhR92njFv2jq6gDo+My6CsOUy8LRHZ5eHV5+kbO7fIZUXlWAn1Ok1V82cN8JEp1XNDF2lRZJ2HzxNZ7WwQUzHUkgOeYNM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
